// flow-typed signature: f6facfc367b96c6ceb2bbe062e7ce408
// flow-typed version: <<STUB>>/esdoc-flow-plugin_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esdoc-flow-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esdoc-flow-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'esdoc-flow-plugin/index' {
  declare module.exports: $Exports<'esdoc-flow-plugin'>;
}
declare module 'esdoc-flow-plugin/index.js' {
  declare module.exports: $Exports<'esdoc-flow-plugin'>;
}
