// flow-typed signature: d02db9738ea557eefeb4bb9978702aa2
// flow-typed version: <<STUB>>/esformatter-collapse-objects_v^0.5.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-collapse-objects'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-collapse-objects' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-collapse-objects/test/compare.spec' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/input-depth' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/input-keycount' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/input-linelength' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/input-objectexpression' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/output-depth-negative' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/output-depth' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/output-keycount-0' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/output-keycount-2' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/output-keycount-negative' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/output-keycount' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/output-linelength' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/arrays/output-objectexpression' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/input-depth' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/input-keycount' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/input-linelength' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/input-objectexpression' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/output-depth-negative' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/output-depth' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/output-keycount-0' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/output-keycount-2' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/output-keycount-negative' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/output-keycount' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/output-linelength' {
  declare module.exports: any;
}

declare module 'esformatter-collapse-objects/test/compare/objects/output-objectexpression' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-collapse-objects/index' {
  declare module.exports: $Exports<'esformatter-collapse-objects'>;
}
declare module 'esformatter-collapse-objects/index.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects'>;
}
declare module 'esformatter-collapse-objects/test/compare.spec.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare.spec'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/input-depth.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/input-depth'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/input-keycount.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/input-keycount'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/input-linelength.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/input-linelength'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/input-objectexpression.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/input-objectexpression'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/output-depth-negative.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/output-depth-negative'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/output-depth.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/output-depth'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/output-keycount-0.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/output-keycount-0'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/output-keycount-2.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/output-keycount-2'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/output-keycount-negative.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/output-keycount-negative'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/output-keycount.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/output-keycount'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/output-linelength.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/output-linelength'>;
}
declare module 'esformatter-collapse-objects/test/compare/arrays/output-objectexpression.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/arrays/output-objectexpression'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/input-depth.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/input-depth'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/input-keycount.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/input-keycount'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/input-linelength.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/input-linelength'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/input-objectexpression.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/input-objectexpression'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/output-depth-negative.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/output-depth-negative'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/output-depth.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/output-depth'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/output-keycount-0.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/output-keycount-0'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/output-keycount-2.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/output-keycount-2'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/output-keycount-negative.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/output-keycount-negative'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/output-keycount.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/output-keycount'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/output-linelength.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/output-linelength'>;
}
declare module 'esformatter-collapse-objects/test/compare/objects/output-objectexpression.js' {
  declare module.exports: $Exports<'esformatter-collapse-objects/test/compare/objects/output-objectexpression'>;
}
