// flow-typed signature: 3be9e79dfc16e6b698c683be11257518
// flow-typed version: <<STUB>>/esformatter-eol-last_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-eol-last'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-eol-last' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esformatter-eol-last/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esformatter-eol-last/index' {
  declare module.exports: $Exports<'esformatter-eol-last'>;
}
declare module 'esformatter-eol-last/index.js' {
  declare module.exports: $Exports<'esformatter-eol-last'>;
}
declare module 'esformatter-eol-last/test/test.js' {
  declare module.exports: $Exports<'esformatter-eol-last/test/test'>;
}
