// flow-typed signature: 5aa35521a33541ce5194f306b1f3966b
// flow-typed version: <<STUB>>/esformatter-braces_v^1.2.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esformatter-braces'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'esformatter-braces' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'esformatter-braces/index' {
  declare module.exports: $Exports<'esformatter-braces'>;
}
declare module 'esformatter-braces/index.js' {
  declare module.exports: $Exports<'esformatter-braces'>;
}
