// flow-typed signature: 0573b43bc8c0015b37114ac70c89f2f9
// flow-typed version: <<STUB>>/fs-extra-promise_v^0.4.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-extra-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-extra-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-extra-promise/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-extra-promise/lib/index.js' {
  declare module.exports: $Exports<'fs-extra-promise/lib/index'>;
}
