// flow-typed signature: 39c16956573e201249ead2c5f437eed8
// flow-typed version: <<STUB>>/gulp-esdoc_v^0.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-esdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-esdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-esdoc/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-esdoc/index' {
  declare module.exports: $Exports<'gulp-esdoc'>;
}
declare module 'gulp-esdoc/index.js' {
  declare module.exports: $Exports<'gulp-esdoc'>;
}
declare module 'gulp-esdoc/test/main.js' {
  declare module.exports: $Exports<'gulp-esdoc/test/main'>;
}
