// flow-typed signature: 0ef727cb31abd88cc5a525a9f4def83b
// flow-typed version: <<STUB>>/gulp-debug_v^3.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-debug' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-debug/index' {
  declare module.exports: $Exports<'gulp-debug'>;
}
declare module 'gulp-debug/index.js' {
  declare module.exports: $Exports<'gulp-debug'>;
}
