// flow-typed signature: bff55c62afea520484d2e8e85cadb14e
// flow-typed version: <<STUB>>/jsdoc-strip-async-await_v^0.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdoc-strip-async-await'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdoc-strip-async-await' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jsdoc-strip-async-await/index' {
  declare module.exports: $Exports<'jsdoc-strip-async-await'>;
}
declare module 'jsdoc-strip-async-await/index.js' {
  declare module.exports: $Exports<'jsdoc-strip-async-await'>;
}
