// flow-typed signature: 00fee50c5c3478397a248259e2f49c16
// flow-typed version: <<STUB>>/p-wait-for_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-wait-for'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-wait-for' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'p-wait-for/index' {
  declare module.exports: $Exports<'p-wait-for'>;
}
declare module 'p-wait-for/index.js' {
  declare module.exports: $Exports<'p-wait-for'>;
}
